version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:ubuntu-16.04_ocaml-4.06.0
    environment:
      TERM: "dumb"
    working_directory: ~/repo
    steps:
      - checkout

      - run: |
          sudo apt-get update &&
          sudo apt-get install -y wget libffi-dev m4 pkg-config

      - run: |
          wget "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.4.0.tar.gz" -O libtensorflow.tar.gz &&
          sudo tar -zxvf libtensorflow.tar.gz -C /usr &&
          rm libtensorflow.tar.gz

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "tensorflow.opam" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-

      - run: |
          eval $(opam config env) &&
          opam pin add tensorflow . -n -y &&
          opam install tensorflow -v -y

      # - save_cache:
      #     paths:
      #       - ~/.opam
      #     key: v1-dependencies-{{ checksum "tensorflow.opam" }}
      
      - run: |
          eval $(opam config env) &&
          cd examples/basics/ &&
          jbuilder build forty_two.exe
      
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: "."
          # Must be relative path from root
          paths:
            - "*"

  test:
    docker:
      - image: tensorflow/tensorflow:1.4.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: "."
      - run: |
          cd examples/basics/ &&
          ./forty_two.native

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
